quiz/urls.py
from django.urls import path, include
from .views import StartView, TestsView, StartTestView, ResultTestView, HistoryTopicView, HistoryAllTopicView, del_q_marks, view_errors, search_tests



urlpatterns = [
    path('topics/', StartView.as_view(), name='all_topics'),
    path('topics/<int:topic>/', TestsView.as_view(), name='tests'),
    path('topics/<int:topic>/test/<int:test>/', StartTestView.as_view(), name='start_test'),
    path('topics/<int:topic>/test/<int:test>/res/', ResultTestView.as_view(), name='test_res'),
    path('topics/<int:topic>/test/<int:test>/again/', del_q_marks, name='reset_start_test'),
    path('topics/<int:topic>/hist/', HistoryTopicView.as_view(), name='history_tests'),
    path('topics/allhist/', HistoryAllTopicView.as_view(), name='history_topics'),
    path('topics/err/<int:test_mark>/', view_errors, name='test_errors'),
    path('topics/search/', search_tests, name="search")
]

tests_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login_view


urlpatterns = [
    path('', login_view),
    path('admin/', admin.site.urls),
    path('quiz/', include(('quiz.urls', 'quiz'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models
from accounts.models import User
from django.db.models import CharField, ForeignKey, BooleanField, TextField, DateTimeField, ImageField
from django.utils.html import format_html
from django.utils import timezone


class Topic(models.Model):
    name = CharField(max_length=200, unique=True, verbose_name='НАБОР')
    about = CharField(max_length=200, null=True, blank=True, verbose_name='Описание')
    notice = TextField(max_length=200, null=True, blank=True, verbose_name='Примечание')
    picture = ImageField(upload_to='topic_pics/', null=True, blank=True)
    trash_bin = BooleanField(default=False, editable=False)

    class Meta:
        verbose_name = 'Набор тестов'
        verbose_name_plural = 'Наборы тестов'

    def __str__(self):
        return self.name


class Quiz(models.Model):
    name = CharField(max_length=200, verbose_name='ТЕСТ', unique=True)
    topic = ForeignKey(Topic, verbose_name='НАБОР', on_delete=models.SET_NULL, null=True, blank=True)
    editing = BooleanField(default=True, verbose_name='Выбран для редактирования')

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

    def question_text(self):
        try:
            Quiz.objects.filter(name=self.name)[0:1].get()
            qs = self.question_set.all().values()
            count = self.question_set.count()
            html_open = '<span><b><ul style="display: inline; text-align: left;">'
            html_close = '</ul></b></span>'
            if count > 0:
                for i in qs:
                    if i["accepted"] == False:
                        symbol = '<img src="/static/admin/img/icon-no.svg" alt="Нет">'
                    else:
                        symbol = '<img src="/static/admin/img/icon-yes.svg" alt="Да">'
                    html_tmp = '<li><pre style="padding-left: 0; margin: 0;">' + f'{symbol}' + '  ' + f'{i["text"]}' + '</pre></li>'
                    html_open += html_tmp
                html_ok = html_open + html_close
            else:
                html_ok = '<span><img src="/static/admin/img/icon-alert.svg" alt="Упс!">Вопросы не заданы</span>'
        except Quiz.DoesNotExist:
            html_ok = '<span><img src="/static/admin/img/icon-alert.svg" alt="Упс!">Сохраните ТЕСТ!</span>'
        return format_html(html_ok)

    question_text.short_description = "Вопросы теста"

    def __str__(self):
        return self.name


class Question(models.Model):
    text = CharField(max_length=500, verbose_name='ВОПРОС')
    quiz = ForeignKey(Quiz, verbose_name='ТЕСТ', on_delete=models.CASCADE)
    topic_name = ForeignKey(Topic, verbose_name='НАБОР', on_delete=models.SET_NULL, null=True, blank=True)
    accepted = BooleanField(default=False, verbose_name='Активирован')

    class Meta:
        verbose_name = 'Вопрос-Ответы'
        verbose_name_plural = 'Вопросы-Ответы'

    def save(self, *args, **kwargs):
        self.topic_name = self.quiz.topic
        super().save(*args, **kwargs)

    def option_text(self):
        try:
            Question.objects.filter(text=self)[0:1].get()
            qs = self.option_set.all().values()
            count = self.option_set.count()
            html_open = '<span><b><ul style="display: inline; text-align: left;">'
            html_close = '</ul></b></span>'
            if count > 0:
                for i in qs:
                    if i["is_correct"] == False:
                        symbol = '<img src="/static/admin/img/icon-no.svg" alt="Нет">'
                    else:
                        symbol = '<img src="/static/admin/img/icon-yes.svg" alt="Да">'
                    html_tmp = '<li style="list-style-type: none;"><pre style="padding-left: 0; margin: 0;">' + f'{symbol}' + '  ' + f'{(i["answer_text"])}' + '</pre></li>'
                    html_open += html_tmp
                html_ok = html_open + html_close
            else:
                html_ok = '<span><img src="/static/admin/img/icon-alert.svg" alt="Упс!">Ответы не заданы</span>'
        except Question.DoesNotExist:
            html_ok = '<span><img src="/static/admin/img/icon-alert.svg" alt="Упс!">Сохраните ВОПРОС!</span>'
        return format_html(html_ok)

    option_text.short_description = "Варианты ответов"

    def __str__(self):
        return self.text


class Option(models.Model):
    answer_text = CharField(max_length=200,  verbose_name='Ответ', null=True, blank=True)
    question = ForeignKey(Question,  verbose_name='Вопрос', on_delete=models.CASCADE)
    quiz_name = CharField(max_length=200, verbose_name='ТЕСТ', null=True, blank=True)
    topic_name = CharField(max_length=200, verbose_name='НАБОР', null=True, blank=True)
    is_correct = BooleanField(default=False, verbose_name='правильный ответ')

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def save(self, *args, **kwargs):
        if self.quiz_name is None:
            qstn = Question.objects.filter(id=self.question_id).values().first()
            qz_id = qstn['quiz_id']
            qz = Quiz.objects.filter(id=qz_id).values().first()
            self.quiz_name = qz['name']
            tp_id = qz['topic_id']
            tp = Topic.objects.filter(id=tp_id).values().first()
            self.topic_name = tp['name']
        super().save(*args, **kwargs)

    def __str__(self):
        return self.answer_text


class QuestionMark(models.Model):
    user = ForeignKey(User, verbose_name="Студент", on_delete=models.CASCADE)
    question = ForeignKey(Question, verbose_name="Вопрос из теста", on_delete=models.CASCADE)
    done_correct = BooleanField()
    user_answer = CharField(max_length=200, verbose_name="Ответы студента", null=True, blank=True)
    corr_answer = CharField(max_length=200, verbose_name="Ответы на вопрос", null=True, blank=True)
    processed = BooleanField(default=False)


    def get_corr_answer(self):
        correct_options = Option.objects.filter(question=self.question).filter(is_correct=True).order_by('id').values('id')
        self.corr_answer = []
        for obj in correct_options:
            self.corr_answer.append(str(obj['id']))

    def eval_question(self):
        if list(self.user_answer) == list(self.corr_answer):
            self.done_correct = True
        else:
            self.done_correct = False

    def save(self, *args, **kwargs):
        self.get_corr_answer()
        self.eval_question()
        super().save(*args, **kwargs)


class TestMark(models.Model):
    user = ForeignKey(User, verbose_name="Студент", on_delete=models.CASCADE)
    topic = CharField(max_length=200, verbose_name='Набор', null=True, blank=True)
    quiz = CharField(max_length=200, verbose_name='Тест', null=True, blank=True)
    score = CharField(max_length=50, verbose_name='Оценка', null=True, blank=True)
    date = DateTimeField(default=timezone.now, blank=True)


class ErrorObject(models.Model):
    user = ForeignKey(User, verbose_name="Студент", on_delete=models.CASCADE)
    question = ForeignKey(Question, verbose_name="Вопрос", on_delete=models.CASCADE)
    test_mark = ForeignKey(TestMark, verbose_name="Результат теста", on_delete=models.CASCADE)
    test_date = DateTimeField(blank=True)
    wrong_answers = CharField(max_length=200, verbose_name='Неправильно', null=True, blank=True)

quiz/templates/error.html
{% extends 'base.html' %}

{% block title %}Ошибка обработки результата теста{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ topic_obj }}</li>
  </ol>
</nav>
<div class="row">
    <div style="color: red; text-align: center;">Ой!<br>Что-то пошло не так с обработкой результатов тестирования:<br>необходимо пройти тест еще раз!</div>
    <div class="col-md-10 mx-auto mb-3">
        <table class="table">
             <thead>
                <th>Тест из набора "{{ topic_obj }}"</th>
                <th></th>
            </thead>
            <tbody>
                {% for obj in tests %}
                <tr>
                    <td>{{obj.name}}</a></td>
                    <td><a href="{% url 'quiz:reset_start_test' topic obj.id %}" role="button" class="btn btn-info">Начать тест</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

quiz/templates/history.html
{% extends 'base.html' %}

{% block title %}Результаты тестов{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">История набора тестов "{{ topic_obj }}"</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h4> Набор тестов "{{ topic_obj }}":</h4>
        <table class="table">
             <thead>
                <th>Тест:</th>
                <th>Оценка:</th>
                <th colspan="3">Дата:</th>
            </thead>
            <tbody>
                {% for obj in attempts %}
                <tr>
                    <td>{{ obj.quiz }}</td>
                    <td>{{ obj.score }}</td>
                    <td>{{ obj.date }}</td>
                    <td>{% if obj.score == "100.0%" %}
                            <span style="color: darkgreen">Нет ошибок</span>
                        {% else %}
                            <a href="{% url 'quiz:test_errors' obj.id %}" role="button" class="btn btn-warning">Ошибки</a>
                        {% endif %}
                    </td>
                    <td>
                        {% for key,value in quiz_id_dict.items %}
                            {% if key == obj.quiz %}
                                <a href="{% url 'quiz:reset_start_test' topic value %}" role="button" class="btn btn-info">Пройти тест</a>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

quiz/templates/history_all.html
{% extends 'base.html' %}

{% block title %}Результаты тестов{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">История всех наборов тестов</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h4>Все тесты:</h4>
        <table class="table">
             <thead>
                <th>Набор:</th>
                <th>Тест:</th>
                <th>Оценка:</th>
                <th colspan="3">Дата:</th>
            </thead>
            <tbody>
                {% for obj in attempts %}
                <tr>
                    <td>{{ obj.topic }}</td>
                    <td>{{ obj.quiz }}</td>
                    <td>{{ obj.score }}</td>
                    <td>{{ obj.date }}</td>
                    <td>
                        {% if obj.score == "100.0%" %}
                            <span style="color: darkgreen">Нет ошибок</span>
                        {% else %}
                            <a href="{% url 'quiz:test_errors' obj.id %}" role="button" class="btn btn-warning">Ошибки</a>
                        {% endif %}
                    </td>
                    <td>
                       {% for q_key,q_value in quiz_id_info.items %}
                            {% if q_key == obj.quiz %}
                                {% for t_key,t_value in topic_id_info.items %}
                                    {% if t_key == obj.topic %}
                                        <a href="{% url 'quiz:reset_start_test' t_value q_value %}" role="button" class="btn btn-info">Пройти тест</a>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

quiz/templates/mistakes.html
{% extends 'base.html' %}

{% block title %}Ошибки теста{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
        <li class="breadcrumb-item"><a href="{% url 'quiz:history_tests' topic.id %}">Ошибки набора "{{ topic.name }}"</a></li>
        <li class="breadcrumb-item active" aria-current="page">Тест: "{{ test }}"</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h4>Ошибки теста "{{ test }}" от {{ mark.date }}:</h4>
        <table class="table">
             <thead>
                <th>Вопрос:</th>
                <th>Ответ студента:</th>
                <th>Правильный ответ:</th>
                <th>Ответ засчитан:</th>
            </thead>
            <tbody>
                {% for key,value in errors_dict.items %}
                <tr>
                    <td>{{ key.question }}</td>
                    <td>{% for ans in value.err %}
                            {{ ans }}<br>
                        {% endfor %}
                    </td>
                    <td>
                        {% for opt in value.cor %}
                            {{ opt }}<br>
                        {% endfor %}
                    </td>
                    <td>
                        <img src="/static/admin/img/icon-no.svg" alt="Неправильно">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <table align="center" cellpadding="5" style="border: 1px solid black;">
            <thead>
                <th colspan="4" align="right">Итоговый результат по тесту "{{ test }}" от <b>{{ mark.date }}</b></th>
            </thead>
            <tbody>
                <tr>
                    <td style="border: 1px solid black;">правильных ответов</td>
                    <td style="border: 1px solid black;">неправильных ответов</td>
                    <td style="border: 1px solid black;">результат в %</td>
                    <td rowspan="2" style="border: 1px solid black;">
                        <a href="{% url 'quiz:reset_start_test' topic.id test.id %}" role="button" class="btn btn-danger">Пройти тест<br>еще раз</a>
                    </td>
                </tr>
                </tr>
                <tr>
                    <td style="border: 1px solid black;">{{ cor_count }}</td>
                    <td style="border: 1px solid black;">{{ err_count }}</td>
                    <td style="border: 1px solid black;">{{ mark.score }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

quiz/templates/question.html
{% extends 'base.html' %}

{% block title %}Вопрос{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
        <li class="breadcrumb-item"><a href="{% url 'quiz:tests' topic %}">Набор: {{ topic_obj }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Тест: "{{ test }}"</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h3>Тест "{{ test }}":</h3>
        <table class="table">
             <thead>
                <th>{{question}}</th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <form id="question_form" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="q_id" value="{{q_id}}">
                            {% for obj in options %}
                            <input type="checkbox" name="answers" id="{{ obj.id }}" value="{{ obj.id }}">
                            <label class="vCheckboxLabel" for="{{ obj.id }}">{{ obj.answer_text }}</label><br>
                            {% endfor %}
                            <button class="button" type="submit">Принять ответ</button>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    function CheckValidity(e) {
        let checkboxes = document.querySelectorAll('input[type=checkbox]:checked')
        if (checkboxes.length == 0) {
            alert("Необходимо выбрать ответ(ы) на вопрос.")
            e.preventDefault()
        }
        return true
    }
    let questionForm = document.getElementById("question_form")
    questionForm.addEventListener("submit", CheckValidity, false)
</script>
{% endblock %}

quiz/templates/result.html
{% extends 'base.html' %}

{% block title %}Результат теста{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h3> Тест "{{ test_obj }}":</h3>
        <table class="table">
             <thead>
                <th>Вопрос:</th>
                <th>Ответ студента:</th>
                <th>Правильный ответ:</th>
                <th>Ответ засчитан:</th>
            </thead>
            <tbody>
                {% for obj in marks %}
                <tr>
                    <td>{{ obj.question }}</td>
                    <td>
                        {% for key,value in u_a_dict.items %}
                            {% if key == obj %}
                                {% for val in value %}
                                    {{ val }}<br>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for key,value in c_a_dict.items %}
                            {% if key == obj %}
                                {% for val in value %}
                                    {{ val }}<br>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% if obj.done_correct %}
                            <img src="/static/admin/img/icon-yes.svg" alt="Правильно">
                        {% else %}
                            <img src="/static/admin/img/icon-no.svg" alt="Неправильно">
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <table align="center" cellpadding="5" style="border: 1px solid black;">
            <thead>
                <th colspan="4" align="right">Итоговый результат по тесту "{{ test_obj }}" от <b>{{ date }}</b></th>
            </thead>
            <tbody>
                <tr>
                    <td style="border: 1px solid black;">правильных ответов</td>
                    <td style="border: 1px solid black;">неправильных ответов</td>
                    <td style="border: 1px solid black;">результат в %</td>
                    <td rowspan="2" style="border: 1px solid black;">
                        <a href="{% url 'quiz:reset_start_test' topic test %}" role="button" class="btn btn-danger">Пройти тест<br>еще раз</a>
                    </td>
                </tr>
                </tr>
                <tr>
                    <td style="border: 1px solid black;">{{ correct }}</td>
                    <td style="border: 1px solid black;">{{ wrong }}</td>
                    <td style="border: 1px solid black;">{{ score }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

quiz/templates/search_error.html
{% extends 'base.html' %}

{% block title %}Найти тест{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">Результаты поиска</li>
  </ol>
</nav>
<div class="row">
    <div style="color: red; text-align: center;">Ой!<br>Что-то пошло не так с обработкой результатов поиска:<br>Пожалуйста, повторите поиск!<br>=)</div>
</div>
{% endblock %}

quiz/templates/search_tests.html
{% extends 'base.html' %}

{% block title %}Найти тест{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">Результаты поиска</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        {% if searched %}
            <h4>По запросу "{{ searched }}" {{ reply }}</h4>
            <table class="table">
                <thead>
                    <th>Название теста:</th>
                    <th colspan="2">Из набора тестов:</th>
                </thead>
                <tbody>
                    {% for obj in search_result %}
                        <tr>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.topic }}</td>
                            <td><a href="{% url 'quiz:reset_start_test' obj.topic.id obj.id %}" role="button" class="btn btn-info">Начать тест</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h4>Нет подходящих результатов, приводим полный список тестов:</h4>
            <table class="table">
                <thead>
                    <th>Название теста:</th>
                    <th colspan="2">Из набора тестов:</th>
                </thead>
                <tbody>
                    {% for obj in search_result %}
                        <tr>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.topic }}</td>
                            <td><a href="{% url 'quiz:reset_start_test' obj.topic.id obj.id %}" role="button" class="btn btn-info">Начать тест</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</div>
{% endblock %}

quiz/templates/start.html
{% extends 'base.html' %}

{% block title %}Выберите тему для тестирования{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h3>Все темы тестирования:</h3>
        <table class="table">
             <thead>
                <th>Набор тестов</th>
                <th>Описание</th>
                <th>Примечание</th>
                <th></th>
            </thead>
            <tbody>
                {% for obj in topics %}
                <tr>
                    <td><a href="#" role="button" class="btn btn-success">{{obj.name}}</a></td>
                    <td>{{obj.about}}</td>
                    <td>{{obj.notice}}</td>
                    <td><a href="{% url 'quiz:tests' obj.id %}" role="button" class="btn btn-info">Список тестов</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-8 mx-auto">
        <a href="{% url 'quiz:all_topics' %}"role="button" class="btn btn-info">Все темы</a>
        <a href="{% url 'quiz:all_topics' %}"role="button" class="btn btn-info">Результаты</a>
    </div>
</div>
{% endblock %}

quiz/templates/start_new.html
{% extends 'base.html' %}

{% block title %}Выберите тему для тестирования{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h4>Наборы тестов:</h4>
        <div class="row">
            {% for obj in topics %}
            <div class="card" style="width: 18rem; margin: 15px 20px;">
                {% if obj.picture.url != None %}
                    <img src={{ obj.picture.url }} class="card-img-top" alt="лого_теста">
                {% else %}
                    <img src='...' class="card-img-top" alt="лого_теста">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ obj.name }}</h5>
                    <p class="card-text">{{ obj.about }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% for i in obj.quiz_set.all %}
                    <li class="list-group-item">{{ i }}</li>
                    {% endfor %}
                </ul>
                <div class="card-body">
                    <a href="{% url 'quiz:history_tests' obj.id %}" class="btn btn-outline-secondary">История</a>
                    <a href="{% url 'quiz:tests' obj.id %}" class="btn btn-outline-primary">Список тестов</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/tests.html
{% extends 'base.html' %}

{% block title %}Выберите тест{% endblock %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:all_topics' %}">Начало</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ topic }}</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-10 mx-auto mb-3">
        <h4> Тесты из набора "{{ topic }}":</h4>
        <table class="table">
             <thead>
                <tr>{{ topic.about }}</tr>
                <tr>
                    <th colspan="2">Тест</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in tests %}
                <tr>
                    <td>{{obj.name}}</a></td>
                    <td><a href="{% url 'quiz:reset_start_test' topic.id obj.id %}" role="button" class="btn btn-info">Начать тест</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}